### ISSUE TITLE
Type mismatch: inferred type is GoogleSignInAccount? but GoogleSignInAccount was expected

### ISSUE THREAD

**Issue by rogerkamal** [FrangSierra/KotlinFirechat#1]
![error](https://user-images.githubusercontent.com/43880301/49628817-696b6e80-fa0c-11e8-8392-e3cb4e14085f.png)
Well. I'm a beginner with Firebase  & Kotlin. Please Help
Below is my code
  

override fun onGoogleCredentialReceived(credential: AuthCredential, account: GoogleSignInAccount?) {
        showProgressDialog("Creating account")
        dispatcher.dispatch(CreateAccountWithProviderCredentialsAction(credential, GoogleSignInApiUtils.getUserData(account)))
        sessionStore.flowable()
            .filterOne { it.createAccountTask.isTerminal() } //Wait for request to finish
            .subscribe {
                if (it.createAccountTask.isSuccessful() && it.loggedUser != null) {
                    if (it.verified) goToHome() else goToVerificationEmailScreen()
                } else if (it.createAccountTask.isFailure()) {
                    it.createAccountTask.error?.let {
                        toast(errorHandler.getMessageForError(it))
                    }
                }
                dismissProgressDialog()
            }.track()
    }

**Comment by rogerkamal** [comment]
Okay I created SHA - 1 Key Successfully and put in Firebase console

Now I'm getting a new error
E/ViewRootImpl: sendUserActionEvent() mView == null

**Comment by rogerkamal** [comment]
![error](https://user-images.githubusercontent.com/43880301/49637436-62a02400-fa2b-11e8-93f0-953f69c8083e.png)
![image](https://user-images.githubusercontent.com/43880301/49637499-8d8a7800-fa2b-11e8-9b1a-be2de4b4ff5c.png)

**Comment by FrangSierra** [comment]
Hello @rogerkamal, The API of the Google authentication have change, together with the Firebase version. You should update it :) Do the proper changes that you need in the code, I will upload the fix on the next article of the Firebase Series after update the dependencies

**Comment by rogerkamal** [comment]
Actually I don't know How to solve it , I 'm workin in Firebase first time, Check my logcat . Please provide me full solution.
![error](https://user-images.githubusercontent.com/43880301/49684882-06f39a80-fb00-11e8-9628-26dcc845dee7.png)

**Comment by rogerkamal** [comment]
@FrangSierra Where do I need to change exactly? Do I need to change in LoginActivity.kt too or only API needs to be changed ?
Please guide appropriately.
Thanks

**Comment by FrangSierra** [comment]
Hello @rogerkamal ,
it's a Kotlin missmatch because the API changes, not a Firebase one.
Just change the code to be like:

```
 fun manageGoogleResult(requestCode: Int, data: Intent?) {
        // Result returned from launching the Intent from GoogleSignInApi.getSignInIntent(...);
        if (requestCode == RC_SIGN_IN) {
            val task = GoogleSignIn.getSignedInAccountFromIntent(data)
            try {
                val account = task.getResult(ApiException::class.java)
                if (account == null){
                    onGoogleSignInFailed(ApiException(Status.RESULT_INTERNAL_ERROR))
                }
                val credential = GoogleAuthProvider.getCredential(account!!.idToken, null)
                onGoogleCredentialReceived(credential, account)
            } catch (e: ApiException) {
                Grove.w { "Google sign in failed with error ${e.message}" }
                onGoogleSignInFailed(e)
            }

        }
    }
```

**Comment by rogerkamal** [comment]
@FrangSierra I don't know what is the problem, I made the above changes in code. But then,
when I run the app I get the errors are as below:
E/FirebaseInstanceId: Failed to resolve target intent service, skipping classname enforcement
E/FirebaseInstanceId: Error while delivering the message: ServiceIntent not found.

Also, when I login to the app with my google id on my galaxy note 3 it gave , error as below:
E/ViewRootImpl: sendUserActionEvent() mView == null.

Do you have run this app successfully by using your Firebase credentials? It might be giving errors because the same app has been installed by use of your credentials and others credentials??

**Comment by FrangSierra** [comment]
Hello @rogerkamal ,
The app works, no matter if the credentials have been used or not. Maybe the user is already registered, just debug the logs and check it. In other hand, maybe Google sign is is not working because you didnt enabled it on Firebase.

Research and study about Firebase, Kotlin and the errors that you could find, it's the best way to learn about it. Stackoverflow and google knows more than me and possibly will answer your questions quite more fast.

**Comment by rogerkamal** [comment]
Hi @FrangSierra ,
I figured out studied about google sign in and made changes whatever needed. 
But now I'm getting run time error as below:
E/MultiWindowProxy: getServiceInstance failed!

Couldn't login app. Please help
